### ISSUE TITLE
utxosList for manual utxo selection not in sync

### ISSUE THREAD

**Issue by mr-zwets** [CashScript/cashscript-playground#2]
The state of the displayed utxoList for manual utxo selection in `contractFunction` is not in sync with the displayed contract uxtos & wallet utxos.

Currently the displayed utxoList for manual utxo selection refreshes state when manual utxo selection switch toggled.
Not sure how to proceed:
- should the state depend upon the contract utxos & wallet utxos (but not refresh)
- or should it refresh and get the latest state (but not depend upon the the contract utxos & wallet utxos if they change later)

**Comment by StrungSafe** [comment]
1) I think inverting how the utxosList will resolve the issue...pass from ContractInfo into ContractFunctions. This will keep the ContractInfo and ContractFunctions in sync and any user initiated action will update the same list

2) Although it could be helpful to add a timer so that the list is auto-refreshed instead of having to be a user event driven update

Maybe something like https://github.com/CashScript/cashscript-playground/compare/main...foldingcash:cashscript-playground:mmolina/utxo-list-sync

**Comment by mr-zwets** [comment]
I think you made a good start having the contract utxos synced between the contract-info and the contract functions! 👍 

Having a 5-second interval to `updateUtxos` is not ideal, better would be to use an ElectrumNetwork provider to set up a listener to incoming transactions to the smart contract address, then re-fetch the list of contract UTXOs.

For manual UTXO selection, the list of UTXOs of the wallets won't be in sync yet, so that could still be a cause of confusion

**Comment by mr-zwets** [comment]
@StrungSafe I merged your changes to keep the global contractUtxos in sync with the contract utxos displayed in the the contractfunctions when using manual Utxo selection 😄 👍 

I made the changes to have an electrum subsription to the contract address. This way there's no longer a need for a timer to re-fetch the utxos every 5 seconds, so I removed it.

Thanks for the contribution 🙏
